name: Test python/tox

on: [push, pull_request]

jobs:
  test-python-tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./python/tox
        with:
          python-version: '3.10'
