name: Test python/tox

on:
  push:
    paths:
      - 'python/tox/**'
      - '.github/workflows/test-python-tox.yml'
  pull_request:
    paths:
      - 'python/tox/**'
      - '.github/workflows/test-python-tox.yml'

jobs:
  test-python-tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./python/tox
        with:
          python-version: '3.10'
